import { readFileSync } from 'node:fs'
import { test } from 'node:test'
import assert from 'node:assert/strict'

const settingsPage = readFileSync(new URL('../app/pages/settings.vue', import.meta.url), 'utf8')
const useApi = readFileSync(new URL('../app/composables/useApi.ts', import.meta.url), 'utf8')

function providerPresetBlock(serviceType) {
  const presetsStart = settingsPage.indexOf('const providerPresets = {')
  assert.notEqual(presetsStart, -1, 'missing providerPresets')
  const marker = `  ${serviceType}: {`
  const start = settingsPage.indexOf(marker, presetsStart)
  assert.notEqual(start, -1, `missing ${serviceType} provider presets`)
  const end = settingsPage.indexOf('\n  },', start)
  assert.notEqual(end, -1, `unterminated ${serviceType} provider presets`)
  return settingsPage.slice(start, end)
}

test('settings page exposes official provider templates only', () => {
  assert.doesNotMatch(settingsPage, /provider:\s*'chatfire'/i)
  assert.doesNotMatch(settingsPage, /openrouter/i)
  assert.doesNotMatch(settingsPage, /huobaoPreset/i)
  assert.doesNotMatch(settingsPage, /applyHuobaoPreset/i)
  assert.doesNotMatch(settingsPage, /\/huobao-preset/)
  assert.doesNotMatch(useApi, /api\.chatfire\.site/i)
  assert.doesNotMatch(useApi, /applyHuobaoPreset/i)
  assert.doesNotMatch(useApi, /openrouter/i)
  assert.doesNotMatch(useApi, /huobaoPreset/i)
  assert.doesNotMatch(useApi, /\/huobao-preset/)

  assert.match(settingsPage, /const providers = \['gemini', 'openai', 'volcengine', 'minimax', 'comfyui'\]/)
  assert.match(settingsPage, /https:\/\/generativelanguage\.googleapis\.com/)
  assert.match(settingsPage, /https:\/\/api\.openai\.com/)
  assert.match(settingsPage, /https:\/\/ark\.cn-beijing\.volces\.com/)
  assert.match(settingsPage, /http:\/\/127\.0\.0\.1:8188/)
  assert.doesNotMatch(settingsPage, /https:\/\/api\.deepseek\.com/)
  assert.doesNotMatch(settingsPage, /https:\/\/dashscope\.aliyuncs\.com/)
  assert.doesNotMatch(settingsPage, /https:\/\/api\.vidu\.com/)
  assert.doesNotMatch(settingsPage, /\['ali'|'ali',|, 'ali'\]/)
  assert.match(settingsPage, /火宝快捷配置/)
  assert.match(settingsPage, /https:\/\/api\.chatfire\.site/)
  assert.match(settingsPage, /applyHuobaoQuickConfig/)
  assert.doesNotMatch(settingsPage, /https:\/\/api\.minimax\.io/)
})

test('settings page offers official default model IDs', () => {
  assert.match(settingsPage, /gemini-3\.1-pro-preview/)
  assert.match(settingsPage, /gemini-3\.5-flash/)
  assert.match(settingsPage, /gemini-3-flash-preview/)
  assert.match(settingsPage, /gpt-5\.6-terra/)
  assert.match(settingsPage, /deepseek-v4-flash/)
  assert.match(settingsPage, /gemini-3-pro-image/)
  assert.match(settingsPage, /gemini-3\.1-flash-image/)
  assert.match(settingsPage, /gpt-image-2/)
  assert.match(settingsPage, /doubao-seedance-2-0-260128/)
  assert.match(settingsPage, /doubao-seedance-2-0-fast-260128/)
  assert.match(settingsPage, /doubao-seedance-2-0-mini-260615/)
  assert.match(settingsPage, /comfyui-default/)
  assert.match(settingsPage, /comfyui-img2img-default/)
  assert.match(settingsPage, /comfyui-first-last-default/)
  assert.match(settingsPage, /图生图/)
  assert.match(settingsPage, /首尾帧/)
  assert.doesNotMatch(settingsPage, /gpt-5\.4/)
  assert.doesNotMatch(settingsPage, /doubao-seed-1-6/)
  assert.doesNotMatch(settingsPage, /wan2\.6-t2i/)
  assert.doesNotMatch(settingsPage, /wan2\.6-i2v-flash/)
  assert.doesNotMatch(settingsPage, /viduq3-turbo/)
  assert.doesNotMatch(settingsPage, /viduq3-pro/)
  assert.doesNotMatch(settingsPage, /gemini-2\.5-flash/)
  assert.doesNotMatch(settingsPage, /gpt-4\.1-mini/)
  assert.doesNotMatch(settingsPage, /gpt-image-1/)
  assert.doesNotMatch(settingsPage, /gemini-3-pro-image-preview/)
  assert.doesNotMatch(settingsPage, /gemini-3\.1-flash-image-preview/)
  assert.doesNotMatch(settingsPage, /doubao-seedream/)
  assert.doesNotMatch(settingsPage, /speech-2\.8-hd/)
})

test('only text service configs expose the connection test button', () => {
  assert.match(settingsPage, /v-if="st\.type === 'text'" class="btn btn-ghost btn-sm" @click="testExistingCfg\(c\)">测试/)
})

test('settings page only offers supported provider presets', () => {
  assert.doesNotMatch(providerPresetBlock('text'), /minimax|comfyui/i)
  assert.doesNotMatch(providerPresetBlock('image'), /'ali'|minimax/i)
  assert.match(providerPresetBlock('image'), /comfyui/)
  assert.match(providerPresetBlock('img2img'), /gemini/)
  assert.match(providerPresetBlock('img2img'), /comfyui/)
  assert.doesNotMatch(providerPresetBlock('img2img'), /openai|volcengine|minimax/i)
  assert.doesNotMatch(providerPresetBlock('video'), /'ali'|'vidu'/i)
  assert.match(providerPresetBlock('video'), /volcengine/)
  assert.match(providerPresetBlock('video'), /comfyui/)
  assert.match(providerPresetBlock('first_last'), /minimax/)
  assert.match(providerPresetBlock('first_last'), /comfyui/)
  assert.doesNotMatch(providerPresetBlock('first_last'), /openai|volcengine|gemini/i)
  assert.doesNotMatch(settingsPage, /audio:\s*\{/)
})

test('settings page exposes ComfyUI workflow API editor', () => {
  assert.match(settingsPage, /showComfyWorkflowEditor/)
  assert.match(settingsPage, /loadDefaultComfyWorkflow/)
  assert.match(settingsPage, /pickComfyWorkflowFile/)
  assert.match(settingsPage, /onComfyWorkflowFileChange/)
  assert.match(settingsPage, /workflowApiStr/)
  assert.match(settingsPage, /comfyuiDefaultWorkflow/)
  assert.match(settingsPage, /ComfyWorkflowBindings/)
  assert.match(settingsPage, /bindings/)
  assert.match(useApi, /comfyui-default-workflow/)
})

test('ComfyUI bindings component exposes parse and pin mapping UI', () => {
  const bindings = readFileSync(new URL('../app/components/ComfyWorkflowBindings.vue', import.meta.url), 'utf8')
  assert.match(bindings, /parseWorkflow/)
  assert.match(bindings, /autoGuess/)
  assert.match(bindings, /Source/)
  assert.match(bindings, /Target Pin/)
  assert.match(bindings, /Output/)
  assert.match(bindings, /outputPins/)
  assert.match(bindings, /CLIPTextEncode/)
  assert.match(bindings, /LoadImage/)
  assert.match(bindings, /SaveImage/)
  // 参考图槽位按 LoadImage / 占位符 / 已有绑定动态生成，上限对齐项目 9 张
  assert.match(bindings, /MAX_REF_IMAGES\s*=\s*9/)
  assert.match(bindings, /refImageSlotCount/)
  assert.match(bindings, /rankedLoadImagePins/)
  assert.match(bindings, /collectLinkedNodeIds/)
  assert.match(bindings, /数组第/)
  assert.match(bindings, /first_frame/)
  assert.match(bindings, /last_frame/)
  assert.match(bindings, /serviceType === 'first_last'/)
  assert.doesNotMatch(bindings, /image_1',\s*label:\s*'Reference Image 1'/)
})
